### ISSUE TITLE
서브바(추가기능,검색기능) 스타일

### ISSUE THREAD

**Issue by HyunJunPark0** [yolo-wallet/yolo-wallet#17]
# 기능
서브바(추가기능,검색기능) 스타일
# 적용되는 페이지 
landingPage.tsx
# 추가 설명
서브바(추가기능,검색기능) 스타일
# 예상 시작일
7.17
# 예상 완료일
7.18

**Comment by peacepiece7** [comment]
브랜치가 생성되지 않은 이슈이고 done으로 태그를 지정해 주셨기 때문에 해당 이슈는 닫습니다.
